export const initialState = {
  // categories: [
  //   {
  //     id: 1,
  //     name: 'seaside',
  //     title: 'Sunny seaside',
  //     image: '/images/categories/seaside_640.jpg',
  //   },
  //   {
  //     id: 2,
  //     name: 'cities',
  //     title: 'Vibrant cities',
  //     image: '/images/categories/city_640.jpg',
  //   },
  //   {
  //     id: 3,
  //     name: 'mountains',
  //     title: 'Secret mountains',
  //     image: '/images/categories/mountains_640.jpg',
  //   },
  //   {
  //     id: 4,
  //     name: 'countryside',
  //     title: 'Secluded countryside',
  //     image: '/images/categories/countryside_640.jpg',
  //   },
  // ],

  categories: {
    data: [],
    loading: {
      active: false,
      error: false,
    },
  },

  apartments: {
    data: [
      // {
      //   id: 'a1',
      //   category: 'seaside',
      //   name: 'Sea Apartment Lux',
      //   city: 'Barcelona',
      //   location: {lat: 41.38901, lng: 2.19465},
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 500,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'private',
      //   balcony: 1,
      //   image: ['/images/offers/sea1864448_640.jpg', '/images/offers/sea389253_640.jpg', '/images/offers/sea389267_640.jpg'],
      // },
      // {
      //   id: 'a2',
      //   category: 'seaside',
      //   name: 'Beach Apartment Lux',
      //   city: 'Capri',
      //   location: {lat: 40.55083, lng: 14.248302},
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 750,
      //   bedrooms: 5,
      //   kitchen: 2,
      //   swimpool: 'private',
      //   balcony: 2,
      //   image: ['/images/offers/sea3100785_640.jpg', '/images/offers/sea416135_640.jpg', '/images/offers/sea891778_640.jpg'],
      // },
      // {
      //   id: 'a3',
      //   category: 'seaside',
      //   name: 'Ocean Penthouse',
      //   city: 'Laguna Beach',
      //   location: {lat: 33.523028, lng: -117.763304 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 400,
      //   bedrooms: 2,
      //   kitchen: 1,
      //   swimpool: 'public',
      //   balcony: 1,
      //   image: ['/images/offers/sea3715707_640.jpg', '/images/offers/sea943428_640.jpg', '/images/offers/sea1030754_640.jpg'],
      // },
      // {
      //   id: 'a4',
      //   category: 'seaside',
      //   name: 'Baltic Apartment',
      //   city: 'Sopot',
      //   location: {lat: 54.446593, lng: 18.567866 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 500,
      //   bedrooms: 3,
      //   kitchen: 2,
      //   swimpool: 'private',
      //   balcony: 3,
      //   image: ['/images/offers/sea5114392_640.jpg', '/images/offers/sea1362960_640.jpg', '/images/offers/sea1938008_640.jpg'],
      // },
      // {
      //   id: 'a5',
      //   category: 'seaside',
      //   name: 'Atlantic Apartment High',
      //   city: 'Miami',
      //   location: {lat: 25.793631, lng: -80.130601 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 800,
      //   bedrooms: 4,
      //   kitchen: 1,
      //   swimpool: 'public',
      //   balcony: 3,
      //   image: ['/images/offers/sea1030758_640.jpg', '/images/offers/sea2408868_640.jpg', '/images/offers/sea2414599_640.jpg'],
      // },
      // {
      //   id: 'b1',
      //   category: 'cities',
      //   name: 'Westminster Penthouse',
      //   city: 'London',
      //   location: {lat: 51.510286, lng: -0.119406 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 900,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/city460762_640.jpg', '/images/offers/city186699_640.jpg', '/images/offers/city406901_640.jpg'],
      // },
      // {
      //   id: 'b2',
      //   category: 'cities',
      //   name: 'Manhattan Office',
      //   city: 'New York',
      //   location: {lat: 40.76375, lng: -73.97354},
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 700,
      //   bedrooms: 2,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/city1927719_640.jpg', '/images/offers/city407703_640.jpg', '/images/offers/city595121_640.jpg'],
      // },
      // {
      //   id: 'b3',
      //   category: 'cities',
      //   name: 'Japanstyle Penthouse',
      //   city: 'Tokyo',
      //   location: {lat: 35.653319, lng: 139.769155 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 650,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/city2614141_640.jpg', '/images/offers/city690364_640.jpg', '/images/offers/city930804_640.jpg'],
      // },
      // {
      //   id: 'b4',
      //   category: 'cities',
      //   name: 'Koala Apartment',
      //   city: 'Sydney',
      //   location: {lat: -33.849094, lng: 151.218100 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 400,
      //   bedrooms: 2,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/city3137416_640.jpg', '/images/offers/city5502975_640.jpg', '/images/offers/city5502970_640.jpg'],
      // },
      // {
      //   id: 'c1',
      //   category: 'mountains',
      //   name: 'Alpine House',
      //   city: 'Courchevel',
      //   location: {lat: 45.415061, lng: 6.635144 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 400,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 2,
      //   image: ['/images/offers/mount54906_640.jpg', '/images/offers/mount828795_640.jpg', '/images/offers/mount1178278_640.jpg'],
      // },
      // {
      //   id: 'c2',
      //   category: 'mountains',
      //   name: 'Sniezka Resthouse',
      //   city: 'Karpacz',
      //   location: {lat: 50.773194, lng: 15.749862 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 300,
      //   bedrooms: 2,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/mount726325_640.jpg', '/images/offers/mount1737168_640.jpg', '/images/offers/mount2804083_640.jpg'],
      // },
      // {
      //   id: 'c3',
      //   category: 'mountains',
      //   name: 'Caucasian Dream',
      //   city: 'Sochi',
      //   location: {lat: 43.575153, lng: 39.728287 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 600,
      //   bedrooms: 4,
      //   kitchen: 2,
      //   swimpool: 'private',
      //   balcony: 2,
      //   image: ['/images/offers/mount1626578_640.jpg', '/images/offers/mount2930070_640.jpg', '/images/offers/mount3803443_640.jpg'] ,
      // },
      // {
      //   id: 'c4',
      //   category: 'mountains',
      //   name: 'Executive Suite',
      //   city: 'Aspen',
      //   location: {lat: 39.19426, lng: -106.828727 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 400,
      //   bedrooms: 2,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/mount2881296_640.jpg', '/images/offers/mount4013531_640.jpg', '/images/offers/mount4676673_640.jpg'],
      // },
      // {
      //   id: 'c5',
      //   category: 'mountains',
      //   name: 'Transilvania Secret',
      //   city: 'Clusenburg',
      //   location: {lat: 46.77751, lng: 23.598628 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 250,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/mount3178666_640.jpg', '/images/offers/mount4704299_640.jpg', '/images/offers/mount5992184_640.jpg'],
      // },
      // {
      //   id: 'd1',
      //   category: 'countryside',
      //   name: 'Masurian Silence',
      //   city: 'Kruklanki',
      //   location: {lat: 54.096856, lng: 21.933430 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 300,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 1,
      //   image: ['/images/offers/country389264_640.jpg', '/images/offers/country252178_640.jpg', '/images/offers/country356339_640.jpg'],
      // },
      // {
      //   id: 'd2',
      //   category: 'countryside',
      //   name: 'Green Silence',
      //   city: 'Village Corner',
      //   location: {lat: 36.552103, lng: -121.927823 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 450,
      //   bedrooms: 4,
      //   kitchen: 2,
      //   swimpool: 'private',
      //   balcony: 2,
      //   image: ['/images/offers/country1882178_640.jpg', '/images/offers/country806854_640.jpg', '/images/offers/country844269_640.jpg'],
      // },
      // {
      //   id: 'd3',
      //   category: 'countryside',
      //   name: 'Stone Tower',
      //   city: 'Mestia',
      //   location: {lat: 43.030602, lng: 42.689383 },
      //   description: 'Maecenas eget velit non eros vulputate leo ac lacus euismod pede, molestie vitae, cursus a, sodales tempor. Phasellus semper convallis. Praesent tristique enim, sagittis tortor. ',
      //   price: 250,
      //   bedrooms: 3,
      //   kitchen: 1,
      //   swimpool: 'no',
      //   balcony: 2,
      //   image: ['/images/offers/country962240_640.jpg', '/images/offers/country1477041_640.jpg', '/images/offers/country2006992_640.jpg'],
      // },
    ],
    loading: {
      active: false,
      error: false,
    },
    oneApartment: {},
  },

  orders: {
    data: [],
    loading: {
      active: false,
      error: false,
      added: false,
      done: false,
    },
  },
};
